### ISSUE TITLE
More hardware modifications

### ISSUE THREAD

**Issue by mtfurlan** [d1str0/dc29-badge#10]
If you also bridge the other jumper and connect the alien ship to ground you get more stuff
![badge-modifications](https://user-images.githubusercontent.com/1208858/128452310-79e02974-f4fc-4642-a7b9-abd81662a3b3.jpg)

```
Thank you for doing your part to keep the signal going! To continue your journey, go to:
defcon.org/signal/WhatIfIToldYou/YourJourneyBegins
/WatchYourHead
/ItWasTotallyAliens
```

I haven't figured out how to use those URL pieces yet.

Instructions (maybe not originally) from cyberlava in defcon discord.

**Comment by d1str0** [comment]
I was able to reproduce both the bridge in the bottom left producing /WatchYourHead and also the Alien one, unsure how to move forward and unknown if it has anything to do with Jenny.

**Comment by Shadyman** [comment]
Alien ship to the ET touch would work as well, both the ET Touch and the button pin are grounded

**Comment by Shadyman** [comment]
From my rescinded git commit: 

(SPOILERS?)

> After we removed the RED from the picture when we chose the red pill in earlier steps (We saw blue jenny and green jenny, but not red), we had to reconnect the signal in a similar method. There is a second solder jumper that is unsoldered. Short that, restart, and you'll see:

> Thank you for doing your part to keep the signal going! To continue your journey, go to:
defcon.org/signal/WhatIfIToldYou/YourJourneyBegins
>/WatchYourHead

It seemed to fit the narrative and made sense with the lack of RED from the red pill we cut out earlier.

**Comment by lukaskuzmiak** [comment]
This is after I spent way too much time in the firmware :)

```c
if ( TIMES_YOUVE_SHARED_SIGNAL > 19u )
{
  j_uart_send_string("Thank you for doing your part to keep the signal going! To continue your journey, go to:", 89);
  j_uart_send_char('\r');
  j_uart_send_char('\n');
  j_uart_send_string("defcon.org/signal", 18);
  uart_send_decrypted_string(WhatIfIToldYou, 15);
  PORT_IN_val = PORT_A_IN;
  if ( (PORT_IN_val & 0x10000000) != 0 )    // check bit 28, PA28 GPIO - red pill
  {
    uart_send_decrypted_string(YourJourneyBegins, 18);
    PORT_IN_val_1 = PORT_A_IN;
    if ( (PORT_IN_val_1 & 0x8000000) == 0 ) // check bit 27, PA27 GPIO - matrix, bottom left corner pads
    {
      j_uart_send_char('\r');
      j_uart_send_char('\n');
      uart_send_decrypted_string(WatchYourHead, 14);
      PORT_B_IN_val = PORT_B_IN;
      if ( (PORT_B_IN_val & 4) == 0 )       // check bit 2, PB02 GPIO - ufo to ground
      {
        j_uart_send_char('\r');
        j_uart_send_char('\n');
        uart_send_decrypted_string(ItWasTotallyAliens, 19);
      }
    }
  }
  j_uart_send_char('\r');
  j_uart_send_char('\n');
}
```

**Comment by Shadyman** [comment]
So why does it add them with \r\n between instead of a / even though it's a sequential check? They must be somewhere else in the URL tree?

**Comment by lukaskuzmiak** [comment]
@Shadyman ya, that is what I'm assuming as well

**Comment by Shadyman** [comment]
> So why does it add them with \r\n between instead of a / even though it's a sequential check? They must be somewhere else in the URL tree?

Or they're HINTS at a subdirectory and not actually a subdirectory itself. hmm

**Comment by d1str0** [comment]
This has been added to the spoilers :) Thanks!
